apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: db:5432
    database: investment
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1500 # PostgreSQL 15
      timescaledb: true
    isDefault: true
    editable: true
